events { worker_connections 1024; }

http {
  server {
    # this is the port that Nginx container is set up to listen
    listen 80;

    # configure here where requests to http://localhost:8000/...
    # are forwarded
    location / {
      proxy_pass http://frontend:5001;

    }

    # configure here where requests to http://localhost:8000/api/...
    # are forwarded
    location /api/ {
      proxy_set_header Host $host;
      proxy_pass http://backend:8080/;
    }
  }
}
