FROM alpine:3.21

WORKDIR /mydir

RUN apk add --no-cache curl ffmpeg python3 ca-certificates && \
    curl -L https://github.com/yt-dlp/yt-dlp/releases/latest/download/yt-dlp -o /usr/local/bin/yt-dlp && \
    chmod a+x /usr/local/bin/yt-dlp && \
    adduser -D appuser && \
    chown appuser . && \
    apk del curl

USER appuser

ENTRYPOINT ["/usr/local/bin/yt-dlp"]
