FROM golang:1.25-alpine

EXPOSE 8080

WORKDIR /usr/src/app

COPY . .

RUN go build && go test ./...  && \
    adduser -D appuser && chown appuser . && \

USER appuser

CMD ["./server"]

# Size V0: 635MB
# Size V1: 390MB
# Size V2: 320MB
