FROM ubuntu:latest

EXPOSE 5000

WORKDIR /usr/src/app

RUN apt-get update && apt-get install -y curl

RUN curl -sL https://deb.nodesource.com/setup_16.x | bash

RUN apt install -y nodejs

RUN node -v && npm -v

COPY . .

RUN npm install

### Production mode

# Build static files
RUN npm run build

# Install
RUN npm install -g serve

# USER
RUN useradd -m appuser
## give permissions
RUN chown appuser .
## use him
USER appuser

# Serve
CMD ["serve", "-s", "-l", "5000", "build"]
