FROM alpine

EXPOSE 8080

WORKDIR /usr/src/app

COPY . .

RUN apk update && apk add go && \
    go build && go test ./...  && \
    adduser -D appuser && chown appuser . && \
    apk del go

USER appuser

CMD ["./server"]

# Size V0: 635MB
# Size V1: 390MB
