services:
  frontend:
    image: example-frontend
    ports:
      - 5000:5000
  backend:
    image: example-backend
    ports:
      - 8080:8080
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - POSTGRES_PORT=5432
      - POSTGRES_HOST=db
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DATABASE=postgres
    depends_on:
      - db
      - redis
  redis:
    image: redis:alpine
    restart: unless-stopped
  db:
    image: postgres
    restart: unless-stopped
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=postgres
