services:
  proxy:
    image: nginx
    ports:
      - 80:80
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - frontend
      - backend

  frontend:
    image: example-frontend

  backend:
    image:
      example-backend
    environment:
      - REQUEST_ORIGIN=http://localhost:80
      - REDIS_HOST=redis
      - POSTGRES_HOST=db
      - POSTGRES_PASSWORD=example
    depends_on:
      - db
      - redis

  redis:
    image: redis:alpine
    restart: unless-stopped

  db:
    image: postgres
    volumes:
      - type: bind
        source: ./database
        target: /var/lib/postgresql
    restart: unless-stopped
    environment:
      - POSTGRES_PASSWORD=example
